# Configuration file for building Pythia.

# Sub-directories for building from sources and for the final distributable.
# BUILD_DIR is also defined in "src/chevah-bash-tests/shellcheck_tests.sh".
BUILD_DIR="build"
# This is also defined independently in "publish_dist.sh".
DIST_DIR="dist"

UPLOAD_SERVER="bin.chevah.com"
UPLOAD_USER="github-upload"
# testing | production
TARGET_DEPLOY='testing'

PY_VERSION="3.12"
PY_RELEASE="3.12.13"
PBS_RELEASE="20260408"
PYTHIA_RELEASE="${PY_RELEASE}.${PBS_RELEASE}"

# Python modules that have to be built and/or installed in Pythia.
# WARGNING: Also update requirement.txt when this is updated.
PYWIN32_VERSION="308"

# Our custom PyPI server overwrites the default pypi.org option from "build.sh".
PIP_INDEX_URL="https://bin.chevah.com:20443/pypi/simple"

# Array of default pip options.
PIP_ARGS=(\
    --index-url="$PIP_INDEX_URL" \
    --no-warn-script-location \
    )
