# Configuration file for building Pythia.

# Sub-directories for building from sources and for the final distributable.
# BUILD_DIR is also defined in "src/chevah-bash-tests/shellcheck_tests.sh".
BUILD_DIR="build"
# This is also defined independently in "publish_dist.sh".
DIST_DIR="dist"

UPLOAD_SERVER="bin.chevah.com"
UPLOAD_USER="github-upload"
# testing | production
TARGET_DEPLOY='testing'

PY_VERSION="3.14"
PY_RELEASE="3.14.6"
PBS_RELEASE="20260728"
PYTHIA_RELEASE="${PY_RELEASE}.${PBS_RELEASE}"

# Python modules that have to be built and/or installed in Pythia.
# WARNING: Also update requirement.txt when this is updated.
PYWIN32_VERSION="312"

# Our custom PyPI server overwrites the default pypi.org option from "build.sh".
PIP_INDEX_URL="https://bin.chevah.com:20443/pypi/simple"

# Array of default pip options.
PIP_ARGS=(\
    --index-url="$PIP_INDEX_URL" \
    --no-warn-script-location \
    )

DEBUG="${DEBUG-0}"

execute() {
    if [ "$DEBUG" -ne 0 ]; then
        (>&2 echo -e "\tExecuting:" "$@")
    fi

    #Make sure $@ is called in quotes as otherwise it will not work.
    "$@"
    exit_code="$?"
    if [ "$DEBUG" -ne 0 ]; then
        (>&2 echo -e "\tExit code was: $exit_code")
    fi
    if [ "$exit_code" -ne 0 ]; then
        (>&2 echo "PWD :" "$(pwd)")
        (>&2 echo "Fail:" "$@")
        exit 97
    fi
}
