#!/usr/bin/env bash
#
# Uploads dist packages to testing/ on Chevah's server, then shows final links.
# To be used through GitHub actions.

set -o nounset
set -o errexit
set -o pipefail

dest_server="bin.chevah.com"
dest_user="github-upload"
root_link="https://${dest_server}:20443/testing"

# The publish_dist_sftp_batch file is generated by the build process.
# The private key comes from GitHub Secrets through the configured workflow.
sftp_opts="-b publish_dist_sftp_batch -i priv_key -o StrictHostKeyChecking=yes"

# Get OS var and set sftp command accordingly.
source BUILD_ENV_VARS
case $OS in
    win)
        # Upstream SFTP is needed and installed through GitHub actions.
        sftp_cmd="/c/Progra~1/OpenSSH-Win64/sftp.exe"
        ;;
    *)
        sftp_cmd="sftp"
        ;;
esac

$sftp_cmd $sftp_opts ${dest_user}@${dest_server}

# Get DIST_DIR.
source pythia.conf

# Local hierarchy matches the remote one.
upload_dir=$(cd $DIST_DIR && ls -1)
pkg_name=$(cd $DIST_DIR/$upload_dir && ls -1)

echo "Package $pkg_name uploaded to: ${root_link}/${upload_dir}/"
echo "Direct link: ${root_link}/${upload_dir}/${pkg_name}"
