#!/usr/bin/env bash
#
# Uploads dist packages to testing/ on Chevah's server, then shows final links.
# To be used through GitHub actions.

set -o nounset
set -o errexit
set -o pipefail

source build.conf

root_link="https://$UPLOAD_SERVER:20443/testing"

# The build/publish_dist_sftp_batch file is generated by the build process.
# The private key comes from GitHub Secrets through the configured workflow.

target_dir="/${TARGET_DEPLOY}/${PYTHIA_RELEASE}/"
batch_file="${BUILD_DIR}/sftp.batch"
echo "> Uploading to ${target_dir}"
echo "-mkdir ${target_dir}" > "${batch_file}"
echo "mput ${DIST_DIR}/python-*.tar.gz ${target_dir}" >> "${batch_file}"

sftp_opts=(-P 10022 -b ${batch_file} -o IdentityFile=priv_key \
    -o StrictHostKeyChecking=yes)

OS="$(uname -s)"
case "$OS" in
    MINGW*|MSYS*)
        # To use an RSA key, upstream SFTP is installed through GitHub actions.
        sftp_cmd="/c/Progra~1/OpenSSH-Win64/sftp.exe"
        ;;
    *)
        sftp_cmd="sftp"
        ;;
esac

"$sftp_cmd" "${sftp_opts[@]}" "$UPLOAD_USER"@"$UPLOAD_SERVER"

# As dist/ is rebuilt on every build, it should only have 1 sub-dir with 1 pkg.
upload_dir="$(cd "$DIST_DIR" && ls -1)"
pkg_name="$(cd "$DIST_DIR"/"$upload_dir" && ls -1)"

# Local hierarchy matches the remote one.
echo "Package $pkg_name uploaded to: $root_link/$upload_dir/"
echo "Direct link: $root_link/$upload_dir/$pkg_name"
