#!/usr/bin/env bash
#
# Chevah Script for copying required SQLite source and headers.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_build.sh
source ../../"BUILD_ENV_ARRAYS"


chevahbs_getsources() {
    # SQLite has a peculiar naming scheme for downloads.
    # The year probably needs to be updated when updating the version.
    local name="$1"
    local ver="$2"
    local ext="tar.gz"
    local link=https://sqlite.org/2024/"$name"-"$ver"."$ext"

    download_sources "$name" "$ver" "$link" "$ext"
}


chevahbs_configure() {
    # To properly quote multiple options, this is a Bash array.
    CONF_OPTS=(--disable-shared --enable-static)
    execute ./configure --prefix="" "${CONF_OPTS[@]}"
}


chevahbs_compile() {
    execute "${MAKE_CMD[@]}"
}


# FIXME:48:
# Test SQLite when building it from source.
chevahbs_try() {
    execute "${MAKE_CMD[@]}" check
}


chevahbs_cp() {
    execute "${MAKE_CMD[@]}" install DESTDIR="$INSTALL_DIR"
}


select_chevahbs_command "$@"
