#!/usr/bin/env bash
#
# Chevah Build Script for gmpy2 without MPFR and MPC library support.
# Beware that beginning with v2.1.0, MPFR and MPC will be required.
# On Windows, the upstream wheel is used.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_pythia.sh


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="zip"
    local link=https://files.pythonhosted.org/packages/90/f4/9a2e384b325b69bc5827b9a6510a8fb4a51698c915c06a3f25a86458892a/"$name"-"$ver"."$ext"

    download_sources $name $ver $link $ext
}


chevahbs_configure() {
    echo "[build_ext]" >> setup.cfg
    echo "include_dirs=$INSTALL_DIR/include" >> setup.cfg
    echo "library_dirs=$INSTALL_DIR/lib" >> setup.cfg

    # Download deps from our PyPI server and block the official source.
    echo "[easy_install]" >> setup.cfg
    echo "find_links=https://pypi.chevah.com/" >> setup.cfg
    echo "allow_hosts=*pypi.chevah.com*" >> setup.cfg
}


chevahbs_compile() {
    execute $PYTHON_BIN setup.py build --nompfr
}


chevahbs_install() {
    execute $PYTHON_BIN setup.py install
}


select_chevahbs_command $@
