#!/usr/bin/env bash
#
# Chevah Build Script for libffi.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_pythia.sh


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tar.gz"
    local link=ftp://sourceware.org/pub/libffi/"$name"-"$ver"."$ext"

    download_sources $name $ver $link $ext
}


chevahbs_configure() {
    execute ./configure --prefix="" --disable-shared --enable-static
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    case $OS in
        lnx)
            # Installing manually to avoid messing with a lib64/ sub-dir.
            execute cp -v x86*-pc-linux-gnu/.libs/libffi.a "$INSTALL_DIR"/lib/
            execute cp -v x86*-pc-linux-gnu/libffi.la "$INSTALL_DIR"/lib/
            execute cp -v x86*-pc-linux-gnu/include/*.h "$INSTALL_DIR"/include/
            execute mkdir "$INSTALL_DIR"/pkgconfig/
            execute cp -v x86*-pc-linux-gnu/libffi.pc "$INSTALL_DIR"/pkgconfig/
            ;;
        *)
            execute $MAKE install DESTDIR=$INSTALL_DIR
            ;;
    esac
}

select_chevahbs_command $@
