#!/usr/bin/env bash
#
# Chevah Build Script for libffi.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_build.sh
source ../../"$BUILD_ENV_ARRAYS_FILE"


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tar.gz"
    local link=https://github.com/libffi/libffi/releases/download/v"$ver"/"$name"-"$ver"."$ext"

    download_sources "$name" "$ver" "$link" "$ext"
}


chevahbs_configure() {
    # To properly quote multiple options, this is a Bash array.
    CONF_OPTS=(--disable-shared --enable-static)
    execute ./configure --prefix="" "${CONF_OPTS[@]}"
}


chevahbs_compile() {
    execute "${MAKE_CMD[@]}"
}


chevahbs_install() {
    case "$OS" in
        linux*)
            echo "Installing manually to avoid messing with a lib64/ sub-dir:"
            execute cp -v ./*-linux-*/.libs/libffi.a "$INSTALL_DIR"/lib/
            execute cp -v ./*-linux-*/libffi.la "$INSTALL_DIR"/lib/
            execute cp -v ./*-linux-*/include/*.h "$INSTALL_DIR"/include/
            execute mkdir "$INSTALL_DIR"/lib/pkgconfig/
            execute cp -v ./*-linux-*/libffi.pc "$INSTALL_DIR"/lib/pkgconfig/
            ;;
        *)
            execute "${MAKE_CMD[@]}" install DESTDIR="$INSTALL_DIR"
            ;;
    esac
}

select_chevahbs_command "$@"
