#!/usr/bin/env bash
#
# Chevah Build Script for Python under Windows.
# There is no actual build, just getting binaries and installing them as needed.


# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_build.sh

# The usual two arguments, e.g. "Python" and "3.9.0",
# but the installation path is also needed, because this script is special.
NAME=$1
VER=$2
# There's no intrinsic need for this, but Chevah's server likes it this way.
INSTALL_DIR=$3/lib

# Construct the relevant download link for the Windows version.
EXT="amd64.zip"
ARCHIVE="python-${VER}.${EXT}"
LINK="https://www.python.org/ftp/python/${VER}/python-${VER}-embed-${EXT}"

# Download without unpacking (amd64.zip extension is treated specially).
download_sources $NAME $VER $LINK $EXT

# Installation consists of unpacking the ZIP'ed embeddable distribution.
echo "## Extracting ZIP archive to ${INSTALL_DIR}... ##"
execute unzip -q "$ARCHIVE" -d "${INSTALL_DIR}"

echo "## Adding site-packages to python*._pth file... ##"
echo "import site" >> ${INSTALL_DIR}/python310._pth
echo "site.main()" >> ${INSTALL_DIR}/python310._pth
