#!/usr/bin/env bash
#
# Chevah Build Script for Python under Windows.
# There is no actual build, just getting binaries and installing them as needed.


# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_pythia.sh

# The usual two arguments, e.g. "Python" and "3.9.0",
# but the installation path is also needed, because this script is special.
NAME=$1
VER=$2
INSTALL_DIR=$3

# Construct the relevant download link for the Windows version.
EXT="amd64.zip"
if [ "$ARCH" = "x86" ]; then
    EXT="win32.zip"
fi
ARCHIVE="python-${VER}.${EXT}"
LINK=https://www.python.org/ftp/python/"$VER"/python-"$VER"-embed-"$EXT"

# Download without unpacking (uppercase ZIP extension is treated specially).
download_sources $NAME $VER $LINK $EXT

# Installation consists of unpacking the ZIP'ed embeddable distribution.
echo "## Extracting ZIP archive to ${INSTALL_DIR}/lib... ##"
execute unzip -q "$ARCHIVE" -d "${INSTALL_DIR}/lib"

echo "## Adding Python paths... ##"
INSTALL_WIN_PATH=$(cd ${INSTALL_DIR}/lib && pwd -W | sed 's|\/|\\|g')
setx PYTHONPATH "${INSTALL_WIN_PATH};${INSTALL_WIN_PATH}\DLLs;${INSTALL_WIN_PATH}\lib;${INSTALL_WIN_PATH}\lib\plat-win;${INSTALL_WIN_PATH}\lib\site-packages;${INSTALL_WIN_PATH}\lib\Scripts"
> ${INSTALL_DIR}/lib/python38._pth
for path in "\\Python38.zip" "\\" "\\DLLs" "\\lib" "\\lib\plat-win" "\\lib\\site-packages" "\\lib\\Scripts"; do
    echo ${INSTALL_WIN_PATH}$path >> ${INSTALL_DIR}/lib/python38._pth
done
