#!/usr/bin/env bash
#
# Chevah Build Script for Python.
#


# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_pythia.sh


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tgz"
    local link=https://www.python.org/ftp/python/"$ver"/"$name"-"$ver"."$ext"

    download_sources $name $ver $link $ext
}


chevahbs_patch() {
    # Our own patch to avoid compiling certain modules.
    echo "Applying disabled_modules.patch:"
    execute patch < disabled_modules.patch

    # Then we apply features-specific patches.
    if [ "$BUILD_LIBEDIT" = "yes" ]; then
        # Adapted from the v4 patch at https://bugs.python.org/issue13501.
        echo "Applying readline_libedit.patch:"
        execute patch -p0 < readline_libedit.patch
    fi
}


chevahbs_configure() {
    CONFIG_ARGS="--disable-shared"
    CONFIGURE_ENVIRONMENT=""

    echo "Copying our header files among Python's ones..."
    execute cp -r "$INSTALL_DIR"/include/* ./Include/

    case $OS in
        macos*)
            CONFIG_ARGS="${CONFIG_ARGS} --without-gcc"
            ;;
        fbsd*|sol11*)
            LDFLAGS="$LDFLAGS -lncurses"
            ;;
        obsd*)
            # In OpenBSD 6.1 and newer we need to mark the Python binary as
            # "wxneeded" because it breaks the mandatory W^X protection.
            LDFLAGS="$LDFLAGS -Wl,-z,wxneeded"
            ;;
    esac

    # This requires the v4 patch from https://bugs.python.org/issue13501.
    if [ "$BUILD_LIBEDIT" = "yes" ]; then
        CONFIG_ARGS="${CONFIG_ARGS} --with-readline=editline"
    fi

    echo "Patching the git rev id into Python's version string..."
    execute cp Modules/getbuildinfo.c Modules/getbuildinfo.c.orig
    # Don't use 'sed -i' because that's not supported on macOS 10.13.
    execute sed -e \
        s/gitid\ =\ \"default\"/gitid\ =\ \"$PYTHON_PACKAGE_VERSION\"/g \
        Modules/getbuildinfo.c.orig > Modules/getbuildinfo.c
    execute ./configure --prefix="" $CONFIG_ARGS
    # These files are already created in the Python distribution,
    # but for some strange reason, make tries to recreate them.
    # We just touch them so that make will see them up to date.
    execute touch Include/Python-ast.h Python/Python-ast.c
}


chevahbs_compile() {
    execute $MAKE
}


chevahbs_install() {
    case $OS in
        alpine*)
            # EMUTRAMP required for full functionality under a grsec kernel.
            # Don't use "paxmark", file attributes will be lost when tar'ed.
            # Needed with non-grsec kernels as well, otherwise PAM-related
            # compat tests crash with signal 11 (last tested on Alpine 3.12).
            execute paxctl -cE python
            ;;
    esac

    execute $MAKE install DESTDIR=$INSTALL_DIR
}


select_chevahbs_command $@
