#!/usr/bin/env bash
#
# Chevah Build Script for libedit.

# Import shared code.
source ../../functions.sh
source ../../functions_build.sh
source ../../"$BUILD_ENV_ARRAYS_FILE"


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tar.gz"
    local link=https://thrysoee.dk/editline/"$name"-"$ver"."$ext"

    download_sources "$name" "$ver" "$link" "$ext"
}


chevahbs_patch() {
    # With libedit, terminal state is not properly restored on some OS'es, eg.
    # after exiting the repl on systems with ncurses 6.0, such as Ubuntu 16.04.
    # Patch from https://trac.macports.org/ticket/48807#comment:141.
    # Upstream bugfix (not recommended): https://gnats.netbsd.org/48957.
    echo "# Applying terminal_restore.patch... #"
    execute patch -p0 < terminal_restore.patch
}


chevahbs_configure() {
    # To properly quote multiple options, this is a Bash array.
    CONF_OPTS=(--disable-shared --enable-static)
    case "$OS" in
        sol*)
            # Required when linking to libedit, which has a simpler configure.
            CFLAGS="$CFLAGS -xcode=pic32"
    esac
    execute ./configure --prefix="" "${CONF_OPTS[@]}"
}


chevahbs_compile() {
    case "$OS" in
        sol*)
            # Path to newer awk.
            PATH="/usr/xpg4/bin:$PATH"
            ;;
    esac
    execute "${MAKE_CMD[@]}"
}


chevahbs_install() {
    execute "${MAKE_CMD[@]}" install DESTDIR="$INSTALL_DIR"
}


select_chevahbs_command "$@"
