#!/usr/bin/env bash
#
# Chevah Build Script for xz.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_build.sh
source ../../"BUILD_ENV_ARRAYS"


chevahbs_getsources() {
    local name="$1"
    local ver="$2"
    local ext="tar.gz"
    local link=https://downloads.sourceforge.net/project/lzmautils/"$name"-"$ver"."$ext"

    download_sources "$name" "$ver" "$link" "$ext"
}


chevahbs_configure() {
    # To properly quote multiple options, this is a Bash array.
    CONF_OPTS=(--enable-static --disable-shared)
    execute ./configure --prefix="" "${CONF_OPTS[@]}"
}


chevahbs_compile() {
    execute "${MAKE_CMD[@]}"
}


chevahbs_try() {
    execute "${MAKE_CMD[@]}" check
}


chevahbs_cp() {
    # xz's installation copies binaries too, but there's no need for them.
    execute cp -R src/liblzma/api/* "$INSTALL_DIR"/include/
    execute cp src/liblzma/.libs/liblzma.a "$INSTALL_DIR"/lib/
    execute cp -L src/liblzma/.libs/liblzma.la "$INSTALL_DIR"/lib/
}


select_chevahbs_command "$@"
