#!/usr/bin/env bash
#
# Chevah Build Script for xz.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_build.sh
source ../../"$BUILD_ENV_ARRAYS_FILE"


chevahbs_getsources() {
    local name="$1"
    local ver="$2"
    local ext="tar.gz"
    local link=https://downloads.sourceforge.net/project/lzmautils/"$name"-"$ver"."$ext"

    download_sources "$name" "$ver" "$link" "$ext"
}


chevahbs_configure() {
    # To properly quote multiple options, this is a Bash array.
    CONF_OPTS=(--enable-static --disable-shared)
    execute ./configure --prefix="" "${CONF_OPTS[@]}"
}


chevahbs_compile() {
    execute "${MAKE_CMD[@]}"
}


chevahbs_install() {
    execute "${MAKE_CMD[@]}" install DESTDIR="$INSTALL_DIR"
}


select_chevahbs_command "$@"
