#!/usr/bin/env bash
#
# Chevah Script for copying required scandir tests.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_pythia.sh


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tar.gz"
    local link=https://codeload.github.com/benhoyt/"$name"/"$ext"/v"$ver"

    download_sources $name $ver $link $ext
}


chevahbs_configure() {
    echo "    Nothing to configure for scandir."
}


chevahbs_compile() {
    echo "    Nothing to build for scandir."
}


chevahbs_install() {
    echo "    Nothing to install for scandir."
}


select_chevahbs_command $@
