#!/usr/bin/env bash
#
# Chevah Build Script for OpenSSL.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_pythia.sh


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tar.gz"
    local link=https://www.openssl.org/source/"$name"-"$ver"."$ext"

    download_sources $name $ver $link $ext
}


chevahbs_configure() {
    CONF_OPTS="no-shared"
    # OpenSSL's build requires an absolute path for --prefix,
    # can't use --prefix="" as in the other chevahbs scripts.
    execute ./config --prefix="$INSTALL_DIR" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
    # XXX Fails on Centos 5 under Docker.
    $MAKE test
}


chevahbs_install() {
    execute $MAKE install
}


select_chevahbs_command $@
