#!/usr/bin/env bash
#
# Chevah Build Script for OpenSSL.

# Import shared code.
# The relative paths work in both src/blabla and build/blabla.
source ../../functions.sh
source ../../functions_build.sh


chevahbs_getsources() {
    local name=$1
    local ver=$2
    local ext="tar.gz"
    local link=https://www.openssl.org/source/"$name"-"$ver"."$ext"

    download_sources $name $ver $link $ext
}


chevahbs_configure() {
    CONF_OPTS="no-shared"
    # OpenSSL's build requires an absolute path for --prefix,
    # can't use --prefix="" as in the other chevahbs scripts.
    execute ./config --prefix="$INSTALL_DIR" $CONF_OPTS
}


chevahbs_compile() {
    execute $MAKE
    execute $MAKE test
}


chevahbs_install() {
    case $OS in
        linux*)
            echo "Installing manually to avoid messing with a lib64/ sub-dir:"
            execute cp -v libcrypto.a libssl.a "$INSTALL_DIR"/lib/
            execute cp -rv include/openssl/ "$INSTALL_DIR"/include/
            execute cp -v *.pc "$INSTALL_DIR"/lib/pkgconfig/
            ;;
        *)
            execute $MAKE install
            ;;
    esac
}


select_chevahbs_command $@
